//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFirst1108
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public System.Guid ID { get; set; }
        public string StudentNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public bool Sex { get; set; }
        public System.DateTime BirthDay { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<System.Guid> Department_ID { get; set; }
    
        public virtual DepartMents DepartMents { get; set; }
    }
}
